# Generated by Django 6.0 on 2025-12-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_dado', models.CharField(choices=[('numero', 'Número'), ('porcentagem', 'Porcentagem'), ('tempo', 'Tempo'), ('texto', 'Texto')], default='numero', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=15)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='analises.metrica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Métrica',
                'verbose_name_plural': 'Registros de Métricas',
                'ordering': ['-data'],
            },
        ),
    ]
